/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package newpackage;

import CarParking1.Admin;
import CarParking1.EntryStationOperator;
import static CarParking1.Slot.Slots;
import static CarParking1.Slot.commitToFileS;
import static CarParking1.Slot.loadFromFileS;
import CarParking1.User;
import static CarParking1.User.Users;
import static CarParking1.User.commitToFileU;
import static CarParking1.User.loadFromFileU;
import java.io.File;
import newpackage1.FileManagerBinary;

/**
 *
 * @author Omar
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    
    static int MainCheck = 0;
    
    public MainFrame() {
        initComponents();
        System.out.println(MainCheck);
        if (MainCheck == 0) {
            String ProjectPath = System.getProperty("user.dir");
            System.out.println("Project Path : " + ProjectPath);
            File currentDir = new File(ProjectPath);
            checkDirectorycontents(currentDir);

          Admin a = new Admin();

           User a1 = new Admin();
           a1.setUserName("admin");
           a1.setUserPass("admin");
           a1.setUserRole("Admin");
    
            a.AddUser(a1);
            a.addslots(5);
      
            loadFromFileU();

            System.out.println(Users);
            
            EntryStationOperator en = new EntryStationOperator();
            en.makeFreeSlots();
            loadFromFileS();
            System.out.println(Slots);
            
            MainCheck = 1;
            System.out.println(MainCheck);
        }
        System.out.println(MainCheck);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        User_Btn = new javax.swing.JButton();
        Cust_Btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(901, 604));

        jPanel2.setBackground(new java.awt.Color(255, 210, 86));

        jLabel1.setFont(new java.awt.Font("Serif", 3, 22)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Which type of a User are you ");

        User_Btn.setBackground(new java.awt.Color(255, 255, 255));
        User_Btn.setFont(new java.awt.Font("Serif", 3, 16)); // NOI18N
        User_Btn.setText("User");
        User_Btn.setToolTipText("if you are a user(Admin,Entry Station operator,Exit Station Operator) press on this button");
        User_Btn.setBorderPainted(false);
        User_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                User_BtnActionPerformed(evt);
            }
        });

        Cust_Btn.setBackground(new java.awt.Color(255, 255, 255));
        Cust_Btn.setFont(new java.awt.Font("Serif", 3, 16)); // NOI18N
        Cust_Btn.setText("Customer");
        Cust_Btn.setToolTipText("if you are a customer press on this button");
        Cust_Btn.setBorderPainted(false);
        Cust_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cust_BtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addComponent(User_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(Cust_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(User_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cust_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(107, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Cust_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cust_BtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new CustomerMain().setVisible(true);
    }//GEN-LAST:event_Cust_BtnActionPerformed

    private void User_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_User_BtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new LoginFrame1().setVisible(true);
    }//GEN-LAST:event_User_BtnActionPerformed

    public static void checkDirectorycontents(File dir) {
        FileManagerBinary Fm = new FileManagerBinary();
        File[] files = dir.listFiles();
        boolean SlotFile = true;
        boolean UserFile = true;
        boolean ParkedCarsFile = true;
        boolean ShiftReportFile = true;
        boolean FreeSlotsFile = true;

        for (File file:files){
            if (file.getName().contains("SlotFile.bin")) {
                SlotFile = false;
            }
            if (file.getName().contains("UserFile.bin")) {
                UserFile = false;
            }
            if (file.getName().contains("ParkedCarsFile.bin")) {
                ParkedCarsFile = false;
            }
            if (file.getName().contains("ShiftReportFile.bin")) {
                ShiftReportFile = false;
            }
            if (file.getName().contains("FreeSlotsFile.bin")) {
                FreeSlotsFile = false;
            }
        }

        if (SlotFile) {
            commitToFileS();
        }
        if (UserFile) {
            commitToFileU();
        }
        if (ParkedCarsFile) {
            Fm.write("ParkedCarsFile.bin", Slots);
        }
        if (ShiftReportFile) {
            Fm.write("ShiftReportFile.bin", Slots);
        }
        if (FreeSlotsFile) {
            Fm.write("FreeSlotsFile.bin", Slots);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cust_Btn;
    private javax.swing.JButton User_Btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
